// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hyperlane/core/interchain_security/v1/genesis.proto

package types

import (
	fmt "fmt"
	github_com_bcp_innovations_hyperlane_cosmos_util "github.com/bcp-innovations/hyperlane-cosmos/util"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the ibc client submodule's genesis state.
type GenesisState struct {
	// accounts are the accounts present at genesis.
	Isms                      []*types.Any                `protobuf:"bytes,1,rep,name=isms,proto3" json:"isms,omitempty"`
	ValidatorStorageLocations []*ValidatorStorageLocation `protobuf:"bytes,2,rep,name=validator_storage_locations,json=validatorStorageLocations,proto3" json:"validator_storage_locations,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_908eb45c3c27ef24, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetIsms() []*types.Any {
	if m != nil {
		return m.Isms
	}
	return nil
}

func (m *GenesisState) GetValidatorStorageLocations() []*ValidatorStorageLocation {
	if m != nil {
		return m.ValidatorStorageLocations
	}
	return nil
}

// GenesisStorageLocation stores the information for
// validator, mailbox and storage-location which validators have announced
type ValidatorStorageLocation struct {
	MailboxId        github_com_bcp_innovations_hyperlane_cosmos_util.HexAddress `protobuf:"bytes,1,opt,name=mailbox_id,json=mailboxId,proto3,customtype=github.com/bcp-innovations/hyperlane-cosmos/util.HexAddress" json:"mailbox_id"`
	ValidatorAddress string                                                      `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	Index            uint64                                                      `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	StorageLocation  string                                                      `protobuf:"bytes,4,opt,name=storage_location,json=storageLocation,proto3" json:"storage_location,omitempty"`
}

func (m *ValidatorStorageLocation) Reset()         { *m = ValidatorStorageLocation{} }
func (m *ValidatorStorageLocation) String() string { return proto.CompactTextString(m) }
func (*ValidatorStorageLocation) ProtoMessage()    {}
func (*ValidatorStorageLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_908eb45c3c27ef24, []int{1}
}
func (m *ValidatorStorageLocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorStorageLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorStorageLocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorStorageLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorStorageLocation.Merge(m, src)
}
func (m *ValidatorStorageLocation) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorStorageLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorStorageLocation.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorStorageLocation proto.InternalMessageInfo

func (m *ValidatorStorageLocation) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *ValidatorStorageLocation) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ValidatorStorageLocation) GetStorageLocation() string {
	if m != nil {
		return m.StorageLocation
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "hyperlane.core.interchain_security.v1.GenesisState")
	proto.RegisterType((*ValidatorStorageLocation)(nil), "hyperlane.core.interchain_security.v1.ValidatorStorageLocation")
}

func init() {
	proto.RegisterFile("hyperlane/core/interchain_security/v1/genesis.proto", fileDescriptor_908eb45c3c27ef24)
}

var fileDescriptor_908eb45c3c27ef24 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x8b, 0xd3, 0x40,
	0x18, 0xc6, 0x33, 0xbb, 0x55, 0xd8, 0x51, 0x70, 0x0d, 0x3d, 0x64, 0x57, 0xc8, 0x96, 0x05, 0x21,
	0x22, 0x9d, 0xb1, 0xf6, 0xe8, 0x41, 0x5a, 0x0f, 0x2a, 0x08, 0x42, 0x0a, 0x1e, 0xbc, 0x84, 0x49,
	0x32, 0xa6, 0x03, 0xc9, 0xbc, 0x61, 0x66, 0x12, 0x92, 0x93, 0x5f, 0xc1, 0xaf, 0xe3, 0x37, 0xe8,
	0xb1, 0x47, 0xf1, 0x50, 0xa4, 0xbd, 0xfa, 0x21, 0xa4, 0x99, 0xb6, 0xa2, 0xb4, 0xa0, 0xb7, 0x77,
	0xe6, 0x99, 0xe7, 0xf7, 0xfe, 0x99, 0x17, 0x8f, 0xe7, 0x6d, 0xc9, 0x55, 0xce, 0x24, 0xa7, 0x09,
	0x28, 0x4e, 0x85, 0x34, 0x5c, 0x25, 0x73, 0x26, 0x64, 0xa4, 0x79, 0x52, 0x29, 0x61, 0x5a, 0x5a,
	0x8f, 0x68, 0xc6, 0x25, 0xd7, 0x42, 0x93, 0x52, 0x81, 0x01, 0xf7, 0xf1, 0xc1, 0x44, 0xb6, 0x26,
	0x72, 0xc4, 0x44, 0xea, 0xd1, 0xf5, 0x55, 0x06, 0x90, 0xe5, 0x9c, 0x76, 0xa6, 0xb8, 0xfa, 0x44,
	0x99, 0x6c, 0x2d, 0xe1, 0xba, 0x9f, 0x41, 0x06, 0x5d, 0x48, 0xb7, 0x91, 0xbd, 0xbd, 0xfd, 0x8a,
	0xf0, 0xfd, 0xd7, 0x36, 0xd3, 0xcc, 0x30, 0xc3, 0xdd, 0x00, 0xf7, 0x84, 0x2e, 0xb4, 0x87, 0x06,
	0xe7, 0xc1, 0xbd, 0xe7, 0x7d, 0x62, 0x81, 0x64, 0x0f, 0x24, 0x13, 0xd9, 0x86, 0xdd, 0x0b, 0xf7,
	0x33, 0x7e, 0x54, 0xb3, 0x5c, 0xa4, 0xcc, 0x80, 0x8a, 0xb4, 0x01, 0xc5, 0x32, 0x1e, 0xe5, 0x90,
	0x30, 0x23, 0x40, 0x6a, 0xef, 0xac, 0x03, 0xbc, 0x24, 0xff, 0x54, 0x38, 0xf9, 0xb0, 0x27, 0xcd,
	0x2c, 0xe8, 0xdd, 0x8e, 0x13, 0x5e, 0xd5, 0x27, 0x14, 0x7d, 0xfb, 0x13, 0x61, 0xef, 0x94, 0xcf,
	0x8d, 0x31, 0x2e, 0x98, 0xc8, 0x63, 0x68, 0x22, 0x91, 0x7a, 0x68, 0x80, 0x82, 0x8b, 0xe9, 0xab,
	0xc5, 0xea, 0xc6, 0xf9, 0xbe, 0xba, 0x79, 0x91, 0x09, 0x33, 0xaf, 0x62, 0x92, 0x40, 0x41, 0xe3,
	0xa4, 0x1c, 0x0a, 0x29, 0xa1, 0xb6, 0x50, 0x7a, 0x28, 0x77, 0x98, 0x80, 0x2e, 0x40, 0xd3, 0xca,
	0x88, 0x9c, 0xbc, 0xe1, 0xcd, 0x24, 0x4d, 0x15, 0xd7, 0x3a, 0xbc, 0xd8, 0x61, 0xdf, 0xa6, 0xee,
	0x53, 0xfc, 0xf0, 0xf7, 0x04, 0x98, 0xd5, 0xbd, 0xb3, 0x6d, 0xaa, 0xf0, 0xf2, 0x20, 0xec, 0x7c,
	0x6e, 0x1f, 0xdf, 0x11, 0x32, 0xe5, 0x8d, 0x77, 0x3e, 0x40, 0x41, 0x2f, 0xb4, 0x07, 0xf7, 0x09,
	0xbe, 0xfc, 0x7b, 0x74, 0x5e, 0xaf, 0x23, 0x3c, 0xd0, 0x7f, 0x76, 0x34, 0x15, 0x8b, 0xb5, 0x8f,
	0x96, 0x6b, 0x1f, 0xfd, 0x58, 0xfb, 0xe8, 0xcb, 0xc6, 0x77, 0x96, 0x1b, 0xdf, 0xf9, 0xb6, 0xf1,
	0x9d, 0x8f, 0xef, 0xff, 0xa7, 0x9f, 0xc6, 0x6e, 0xdd, 0xb3, 0x51, 0x74, 0x6c, 0xf1, 0x4c, 0x5b,
	0x72, 0x1d, 0xdf, 0xed, 0xbe, 0x7b, 0xfc, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x31, 0x5f, 0x46, 0x53,
	0xab, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorStorageLocations) > 0 {
		for iNdEx := len(m.ValidatorStorageLocations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorStorageLocations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Isms) > 0 {
		for iNdEx := len(m.Isms) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Isms[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorStorageLocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorStorageLocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorStorageLocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StorageLocation) > 0 {
		i -= len(m.StorageLocation)
		copy(dAtA[i:], m.StorageLocation)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.StorageLocation)))
		i--
		dAtA[i] = 0x22
	}
	if m.Index != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.MailboxId.Size()
		i -= size
		if _, err := m.MailboxId.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Isms) > 0 {
		for _, e := range m.Isms {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorStorageLocations) > 0 {
		for _, e := range m.ValidatorStorageLocations {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *ValidatorStorageLocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MailboxId.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovGenesis(uint64(m.Index))
	}
	l = len(m.StorageLocation)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Isms", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Isms = append(m.Isms, &types.Any{})
			if err := m.Isms[len(m.Isms)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorStorageLocations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorStorageLocations = append(m.ValidatorStorageLocations, &ValidatorStorageLocation{})
			if err := m.ValidatorStorageLocations[len(m.ValidatorStorageLocations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorStorageLocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorStorageLocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorStorageLocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MailboxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MailboxId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageLocation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StorageLocation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
