// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hyperlane/warp/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HypTokenType int32

const (
	// HYP_TOKEN_COLLATERAL ...
	HYP_TOKEN_COLLATERAL HypTokenType = 0
	// HYP_TOKEN ...
	HYP_TOKEN_SYNTHETIC HypTokenType = 1
)

var HypTokenType_name = map[int32]string{
	0: "HYP_TOKEN_COLLATERAL",
	1: "HYP_TOKEN_SYNTHETIC",
}

var HypTokenType_value = map[string]int32{
	"HYP_TOKEN_COLLATERAL": 0,
	"HYP_TOKEN_SYNTHETIC":  1,
}

func (x HypTokenType) String() string {
	return proto.EnumName(HypTokenType_name, int32(x))
}

func (HypTokenType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7372986c61417e18, []int{0}
}

// Params defines the parameters of the module.
type Params struct {
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7372986c61417e18, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// GenesisState is the state that must be provided at genesis.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params     Params     `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Tokens     []HypToken `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens"`
	TokenCount int64      `protobuf:"varint,3,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7372986c61417e18, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetTokens() []HypToken {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *GenesisState) GetTokenCount() int64 {
	if m != nil {
		return m.TokenCount
	}
	return 0
}

type HypToken struct {
	Id               []byte       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator          string       `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	TokenType        HypTokenType `protobuf:"varint,3,opt,name=token_type,json=tokenType,proto3,enum=hyperlane.warp.v1.HypTokenType" json:"token_type,omitempty"`
	OriginMailbox    []byte       `protobuf:"bytes,4,opt,name=origin_mailbox,json=originMailbox,proto3" json:"origin_mailbox,omitempty"`
	OriginDenom      string       `protobuf:"bytes,5,opt,name=origin_denom,json=originDenom,proto3" json:"origin_denom,omitempty"`
	ReceiverDomain   uint32       `protobuf:"varint,6,opt,name=receiver_domain,json=receiverDomain,proto3" json:"receiver_domain,omitempty"`
	ReceiverContract []byte       `protobuf:"bytes,7,opt,name=receiver_contract,json=receiverContract,proto3" json:"receiver_contract,omitempty"`
}

func (m *HypToken) Reset()         { *m = HypToken{} }
func (m *HypToken) String() string { return proto.CompactTextString(m) }
func (*HypToken) ProtoMessage()    {}
func (*HypToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_7372986c61417e18, []int{2}
}
func (m *HypToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HypToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HypToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HypToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HypToken.Merge(m, src)
}
func (m *HypToken) XXX_Size() int {
	return m.Size()
}
func (m *HypToken) XXX_DiscardUnknown() {
	xxx_messageInfo_HypToken.DiscardUnknown(m)
}

var xxx_messageInfo_HypToken proto.InternalMessageInfo

func (m *HypToken) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *HypToken) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *HypToken) GetTokenType() HypTokenType {
	if m != nil {
		return m.TokenType
	}
	return HYP_TOKEN_COLLATERAL
}

func (m *HypToken) GetOriginMailbox() []byte {
	if m != nil {
		return m.OriginMailbox
	}
	return nil
}

func (m *HypToken) GetOriginDenom() string {
	if m != nil {
		return m.OriginDenom
	}
	return ""
}

func (m *HypToken) GetReceiverDomain() uint32 {
	if m != nil {
		return m.ReceiverDomain
	}
	return 0
}

func (m *HypToken) GetReceiverContract() []byte {
	if m != nil {
		return m.ReceiverContract
	}
	return nil
}

func init() {
	proto.RegisterEnum("hyperlane.warp.v1.HypTokenType", HypTokenType_name, HypTokenType_value)
	proto.RegisterType((*Params)(nil), "hyperlane.warp.v1.Params")
	proto.RegisterType((*GenesisState)(nil), "hyperlane.warp.v1.GenesisState")
	proto.RegisterType((*HypToken)(nil), "hyperlane.warp.v1.HypToken")
}

func init() { proto.RegisterFile("hyperlane/warp/v1/types.proto", fileDescriptor_7372986c61417e18) }

var fileDescriptor_7372986c61417e18 = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcf, 0x6e, 0xd3, 0x30,
	0x00, 0xc6, 0x93, 0x6e, 0x74, 0xcc, 0xed, 0xca, 0x66, 0x86, 0xc8, 0x8a, 0xc8, 0xca, 0x04, 0xa2,
	0x1a, 0x6a, 0xa2, 0x95, 0x0b, 0x42, 0x68, 0x52, 0xdb, 0x55, 0x2b, 0xa2, 0x6c, 0x53, 0x9a, 0xcb,
	0xb8, 0x44, 0x6e, 0x62, 0x32, 0x8b, 0xc6, 0x8e, 0x1c, 0xb7, 0xac, 0x6f, 0x80, 0x38, 0xf1, 0x0e,
	0x5c, 0xb8, 0x80, 0x76, 0xe0, 0x21, 0x76, 0x9c, 0x38, 0x71, 0x42, 0xa8, 0x3d, 0xec, 0x35, 0x50,
	0xec, 0xb4, 0xfc, 0x15, 0x97, 0xc8, 0xfe, 0x7d, 0xdf, 0x67, 0x7f, 0xb2, 0x1d, 0x70, 0xfb, 0x64,
	0x1c, 0x63, 0x3e, 0x40, 0x14, 0xdb, 0xaf, 0x11, 0x8f, 0xed, 0xd1, 0x8e, 0x2d, 0xc6, 0x31, 0x4e,
	0xac, 0x98, 0x33, 0xc1, 0xe0, 0xda, 0x5c, 0xb6, 0x52, 0xd9, 0x1a, 0xed, 0x94, 0x37, 0x7c, 0x96,
	0x44, 0x2c, 0xf1, 0xa4, 0xc1, 0x56, 0x13, 0xe5, 0x2e, 0xaf, 0x87, 0x2c, 0x64, 0x8a, 0xa7, 0xa3,
	0x8c, 0xae, 0xa1, 0x88, 0x50, 0x66, 0xcb, 0x6f, 0x86, 0x36, 0x42, 0xc6, 0xc2, 0x01, 0xb6, 0xe5,
	0xac, 0x3f, 0x7c, 0x69, 0x23, 0x3a, 0x56, 0xd2, 0xd6, 0x5d, 0x90, 0x3f, 0x42, 0x1c, 0x45, 0xc9,
	0xe3, 0xf2, 0xdb, 0xcb, 0xb3, 0xed, 0x1b, 0x7f, 0xf4, 0x53, 0xda, 0xd6, 0x47, 0x1d, 0x14, 0xf7,
	0x31, 0xc5, 0x09, 0x49, 0x7a, 0x02, 0x09, 0x0c, 0x9f, 0x80, 0x7c, 0x2c, 0x25, 0x43, 0xaf, 0xe8,
	0xd5, 0x42, 0x7d, 0xc3, 0xfa, 0xab, 0xb9, 0xa5, 0xb2, 0xcd, 0xe5, 0xf3, 0x6f, 0x9b, 0xda, 0x87,
	0xcb, 0xb3, 0x6d, 0xdd, 0xc9, 0x32, 0x70, 0x17, 0xe4, 0x05, 0x7b, 0x85, 0x69, 0x62, 0xe4, 0x2a,
	0x0b, 0xd5, 0x42, 0xfd, 0xd6, 0x3f, 0xd2, 0x9d, 0x71, 0xec, 0xa6, 0x9e, 0xdf, 0xf2, 0x2a, 0x05,
	0x37, 0x41, 0x41, 0x8e, 0x3c, 0x9f, 0x0d, 0xa9, 0x30, 0x16, 0x2a, 0x7a, 0x75, 0xc1, 0x01, 0x12,
	0xb5, 0x52, 0xb2, 0xf5, 0x29, 0x07, 0xae, 0xce, 0x16, 0x80, 0x25, 0x90, 0x23, 0x81, 0xec, 0x59,
	0x74, 0x72, 0x24, 0x80, 0x75, 0xb0, 0xe4, 0x73, 0x8c, 0x04, 0xe3, 0x46, 0xae, 0xa2, 0x57, 0x97,
	0x9b, 0xc6, 0x97, 0xcf, 0xb5, 0xf5, 0xec, 0x64, 0x1b, 0x41, 0xc0, 0x71, 0x92, 0xf4, 0x04, 0x27,
	0x34, 0x74, 0x66, 0x46, 0xb8, 0x0b, 0xd4, 0xf2, 0x5e, 0x7a, 0x5b, 0x72, 0xc3, 0x52, 0x7d, 0xf3,
	0x3f, 0xad, 0xdd, 0x71, 0x8c, 0x9d, 0x65, 0x31, 0x1b, 0xc2, 0x7b, 0xa0, 0xc4, 0x38, 0x09, 0x09,
	0xf5, 0x22, 0x44, 0x06, 0x7d, 0x76, 0x6a, 0x2c, 0xca, 0x3e, 0x2b, 0x8a, 0x3e, 0x57, 0x10, 0xde,
	0x01, 0xc5, 0xcc, 0x16, 0x60, 0xca, 0x22, 0xe3, 0x4a, 0xda, 0xcf, 0x29, 0x28, 0xb6, 0x97, 0x22,
	0x78, 0x1f, 0x5c, 0xe3, 0xd8, 0xc7, 0x64, 0x84, 0xb9, 0x17, 0xb0, 0x08, 0x11, 0x6a, 0xe4, 0x2b,
	0x7a, 0x75, 0xc5, 0x29, 0xcd, 0xf0, 0x9e, 0xa4, 0xf0, 0x01, 0x58, 0x9b, 0x1b, 0x7d, 0x46, 0x05,
	0x47, 0xbe, 0x30, 0x96, 0xe4, 0xae, 0xab, 0x33, 0xa1, 0x95, 0xf1, 0xed, 0x7d, 0x50, 0xfc, 0xb5,
	0x3a, 0x34, 0xc0, 0x7a, 0xe7, 0xf8, 0xc8, 0x73, 0x0f, 0x9f, 0xb5, 0x0f, 0xbc, 0xd6, 0x61, 0xb7,
	0xdb, 0x70, 0xdb, 0x4e, 0xa3, 0xbb, 0xaa, 0xc1, 0x9b, 0xe0, 0xfa, 0x4f, 0xa5, 0x77, 0x7c, 0xe0,
	0x76, 0xda, 0xee, 0xd3, 0xd6, 0xaa, 0x5e, 0x5e, 0x7c, 0xf3, 0xde, 0xd4, 0x9a, 0xce, 0xf9, 0xc4,
	0xd4, 0x2f, 0x26, 0xa6, 0xfe, 0x7d, 0x62, 0xea, 0xef, 0xa6, 0xa6, 0x76, 0x31, 0x35, 0xb5, 0xaf,
	0x53, 0x53, 0x7b, 0xf1, 0x28, 0x24, 0xe2, 0x64, 0xd8, 0xb7, 0x7c, 0x16, 0xd9, 0x7d, 0x3f, 0xae,
	0x11, 0x4a, 0xd9, 0x08, 0x09, 0xc2, 0x68, 0x62, 0xcf, 0x0f, 0xb2, 0xa6, 0xae, 0xc1, 0x3e, 0x55,
	0xcf, 0x4f, 0xfe, 0x1b, 0xfd, 0xbc, 0x7c, 0xaa, 0x0f, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x86,
	0x26, 0x6d, 0xda, 0x3d, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TokenCount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TokenCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Tokens) > 0 {
		for iNdEx := len(m.Tokens) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tokens[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *HypToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HypToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HypToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReceiverContract) > 0 {
		i -= len(m.ReceiverContract)
		copy(dAtA[i:], m.ReceiverContract)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ReceiverContract)))
		i--
		dAtA[i] = 0x3a
	}
	if m.ReceiverDomain != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ReceiverDomain))
		i--
		dAtA[i] = 0x30
	}
	if len(m.OriginDenom) > 0 {
		i -= len(m.OriginDenom)
		copy(dAtA[i:], m.OriginDenom)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OriginDenom)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OriginMailbox) > 0 {
		i -= len(m.OriginMailbox)
		copy(dAtA[i:], m.OriginMailbox)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OriginMailbox)))
		i--
		dAtA[i] = 0x22
	}
	if m.TokenType != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TokenType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.Tokens) > 0 {
		for _, e := range m.Tokens {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.TokenCount != 0 {
		n += 1 + sovTypes(uint64(m.TokenCount))
	}
	return n
}

func (m *HypToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.TokenType != 0 {
		n += 1 + sovTypes(uint64(m.TokenType))
	}
	l = len(m.OriginMailbox)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.OriginDenom)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ReceiverDomain != 0 {
		n += 1 + sovTypes(uint64(m.ReceiverDomain))
	}
	l = len(m.ReceiverContract)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tokens = append(m.Tokens, HypToken{})
			if err := m.Tokens[len(m.Tokens)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenCount", wireType)
			}
			m.TokenCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HypToken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HypToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HypToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id[:0], dAtA[iNdEx:postIndex]...)
			if m.Id == nil {
				m.Id = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenType", wireType)
			}
			m.TokenType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenType |= HypTokenType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginMailbox", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginMailbox = append(m.OriginMailbox[:0], dAtA[iNdEx:postIndex]...)
			if m.OriginMailbox == nil {
				m.OriginMailbox = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverDomain", wireType)
			}
			m.ReceiverDomain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReceiverDomain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverContract", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiverContract = append(m.ReceiverContract[:0], dAtA[iNdEx:postIndex]...)
			if m.ReceiverContract == nil {
				m.ReceiverContract = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
